name: Deploy Conan 2.x Package

on: [push]

jobs:
  deploy:
    name: "Build and Deploy to Mount Olympus"
    runs-on: ubuntu-latest
    container:
      image: "samuelemrys/gcc12-ubuntu18.04:latest"
      options: --user root
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: configure conan
        shell: bash
        run: |
          conan remote add mtolympus https://mtolympus.jfrog.io/artifactory/api/conan/mtolympus-conan
          conan remote login mtolympus ${{ secrets.MOUNT_OLYMPUS_DEPLOYMENT_USER }} -p ${{ secrets.MOUNT_OLYMPUS_DEPLOYMENT_TOKEN }}
          conan profile detect
      - name: create package
        shell: bash
        run: |
          conan create . --user mtolympus --channel stable -pr:h default -pr:b default
      - name: deploy package
        if: github.ref == 'refs/heads/master' && success()
        shell: bash
        run: |
          conan upload pyvenv/*@mtolympus/stable -r mtolympus -c
  windows:
    name: "Build Windows"
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: install conan
        run: |
          pip install conan
      - name: configure conan
        run: |
          conan remote add mtolympus https://mtolympus.jfrog.io/artifactory/api/conan/mtolympus-conan
          conan profile detect
      - name: create package
        run: |
          conan create . --user mtolympus --channel stable -pr:h default -pr:b default

